config/routes.rb
Rails.application.routes.draw do

  get 'contact/index'
  get 'checkout/index'
  get 'blog/index'
  get 'account/index'

  get 'home/index'
  get 'home/show'
  
  resources :accounts
  resources :blogs

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root 'home#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  #
  def index
  end
  
  #
  def contact
  end
  
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/accounts/index.html.haml
.templatemyaccount
  / TITLE BEGINS
  .headerimage{:style => "background-image: url('http://www.themepush.com/demo-kailo/wp-content/uploads/sites/6/2015/03/header.jpg');"}
    .headercontent
      .container
        .row
          .col-md-12
            .fleft
              %h1 My Account
            .fright.breadc
              %a{:href => "index.html"} Home
              \/ My Account
  / TITLE ENDS
  .container.padtop40.padbot50
    .row
      / MAIN CONTENT BEGINS
      .col-md-12
        .wraplogin
          %form#edd_login_form.edd_form{:action => "#", :method => "post"}
            %fieldset
              %legend Log into Your Account
              %p
                %label Username
                %input#edd_user_login.required.edd-input{:name => "edd_user_login", :title => "Username", :type => "text"}
              %p
                %label Password
                %input#edd_user_pass.password.required.edd-input{:name => "edd_user_pass", :type => "password"}
              %p
                %input#edd_login_submit.edd_submit{:type => "submit", :value => "Log In"}
              %p.edd-lost-password
                %a{:href => "myaccount.html#", :title => "Lost Password"}
                  Lost Password?
        %span.or or
        .wrapregister
          %form#edd_register_form.edd_form{:action => "#", :method => "post"}
            %fieldset
              %legend Register New Account
              %p
                %label Username
                %input#edd-user-login.required.edd-input{:name => "edd_user_login", :title => "Username", :type => "text"}
              %p
                %label Email
                %input#edd-user-email.required.edd-input{:name => "edd_user_email", :title => "Email Address", :type => "email"}
              %p
                %label Password
                %input#edd-user-pass.password.required.edd-input{:name => "edd_user_pass", :type => "password"}
              %p
                %label Confirm Password
                %input#edd-user-pass2.password.required.edd-input{:name => "edd_user_pass2", :type => "password"}
              %p
                %input.button{:name => "edd_register_submit", :type => "submit", :value => "Register"}
      / MAIN CONTENT ENDS

app/views/blogs/index.html.erb
<h1>Blog#index</h1>
<p>Find me in app/views/blog/index.html.erb</p>

app/views/checkout/index.html.haml
.templatemyaccount
  / TITLE BEGINS
  .headerimage{:style => "background-image: url('http://www.themepush.com/demo-kailo/wp-content/uploads/sites/6/2015/03/header.jpg');"}
    .headercontent
      .container
        .row
          .col-md-12
            .fleft
              %h1 Checkout
            .fright.breadc
              %a{:href => "index.html"} Home
              \/ Checkout
  / TITLE ENDS
  .container.padtop50.padbot10
    .row
      / MAIN CONTENT BEGINS
      .col-md-12
        #edd_checkout_wrap
          %form#edd_checkout_cart_form{:method => "post"}
            #edd_checkout_cart_wrap
              %table#edd_checkout_cart.ajaxed
                %thead
                  %tr.edd_cart_header_row
                    %th.edd_cart_item_name
                      Item Name
                    %th.edd_cart_item_price
                      Item Price
                    %th.edd_cart_actions
                      Actions
                %tbody
                  / cart item 1
                  %tr.edd_cart_item
                    %td.edd_cart_item_name
                      .edd_cart_item_image
                        %img.attachment-25x25.wp-post-image{:alt => "172_1", :height => "25", :src => "http://www.themepush.com/demo-kailo/wp-content/uploads/sites/6/edd/2015/03/172_1-150x150.jpg", :width => "25"}
                      %span.edd_checkout_cart_item_title Eyes Wide Shut
                    %td.edd_cart_item_price
                      $17.00
                    %td.edd_cart_actions
                      %a.edd_cart_remove_item_btn{:href => "checkout.html#"} Remove
                  / cart item 2
                  %tr.edd_cart_item
                    %td.edd_cart_item_name
                      .edd_cart_item_image
                        %img.attachment-25x25.wp-post-image{:alt => "163_1", :height => "25", :src => "http://www.themepush.com/demo-kailo/wp-content/uploads/sites/6/edd/2015/03/163_1-150x150.jpg", :width => "25"}
                      %span.edd_checkout_cart_item_title Travel Fashion
                    %td.edd_cart_item_price
                      $19.00
                    %td.edd_cart_actions
                      %a.edd_cart_remove_item_btn{:href => "checkout.html#"} Remove
                  / cart item 3
                  %tr.edd_cart_item
                    %td.edd_cart_item_name
                      .edd_cart_item_image
                        %img.attachment-25x25.wp-post-image{:alt => "168_1", :height => "25", :src => "http://www.themepush.com/demo-kailo/wp-content/uploads/sites/6/edd/2015/03/168_1-150x150.jpg", :width => "25"}
                      %span.edd_checkout_cart_item_title Bananas
                    %td.edd_cart_item_price
                      $6.50
                    %td.edd_cart_actions
                      %a.edd_cart_remove_item_btn{:href => "checkout.html#"} Remove
                  / cart item 4
                  %tr.edd_cart_item
                    %td.edd_cart_item_name
                      .edd_cart_item_image
                        %img.attachment-25x25.wp-post-image{:alt => "5_1", :height => "25", :src => "http://www.themepush.com/demo-kailo/wp-content/uploads/sites/6/edd/2015/03/5_1-150x150.jpg", :width => "25"}
                      %span.edd_checkout_cart_item_title Sandy Banner
                    %td.edd_cart_item_price
                      $8.00
                    %td.edd_cart_actions
                      %a.edd_cart_remove_item_btn{:href => "checkout.html#"} Remove
                %tfoot
                  %tr.edd_cart_footer_row
                    %td
                      Total:
                      %span.edd_cart_amount{"data-subtotal" => "50.5", "data-total" => "50.5"} $50.50
          #edd_checkout_form_wrap.edd_clearfix
            %form#edd_purchase_form.edd_form{:action => "#", :method => "POST"}
              %fieldset#edd_checkout_user_info
                %p#edd-email-wrap
                  %label.edd-label{:for => "edd-email"}
                    Email Address
                    %span.edd-required-indicator *
                  %span.edd-description We will send the purchase receipt to this address.
                  %input#edd-email.edd-input.required{:name => "edd_email", :placeholder => "Email address", :type => "email", :value => ""}
                %p#edd-first-name-wrap
                  %label.edd-label{:for => "edd-first"}
                    First Name
                    %span.edd-required-indicator *
                  %span.edd-description We will use this to personalize your account experience.
                  %input#edd-first.edd-input.required{:name => "edd_first", :placeholder => "First name", :type => "text", :value => ""}
                %p#edd-last-name-wrap
                  %label.edd-label{:for => "edd-last"}
                    Last Name
                  %span.edd-description We will use this as well to personalize your account experience.
                  %input#edd-last.edd-input{:name => "edd_last", :placeholder => "Last name", :type => "text", :value => ""}
              %fieldset#edd_purchase_submit
                %p#edd_final_total_wrap
                  %strong Purchase Total:
                  %span.edd_cart_amount{"data-subtotal" => "50.5", "data-total" => "50.5"} $50.50
                %input#edd-purchase-button.edd-submit.button{:name => "edd-purchase", :type => "submit", :value => "Pay with PayPal"}
      / MAIN CONTENT ENDS

app/views/contact/index.html.haml
.templatecontact
  %iframe{ src: "https://maps.google.de/maps?hl=de&q=Kattendorf&ie=UTF8&t=&z=8&iwloc=B&output=embed", frameborder: 0, scrolling: "no", marginheight: 0, marginwidth: 0, width: '100%', height: '400px' }
  
  .container.padtop20.padbot50
    .row
      .col-md-7
        .titleborder.left
          %div
            %h4.padbot10 Senden Sie uns eine Nachricht
        .done
          .alert.alert-success
            %button.close{"data-dismiss" => "alert", :type => "button"} ×
            Your message has been sent. Thank you!
        %form#contactform{:action => "contact.php", :method => "post"}
          .form
            %input.col-md-6{:name => "name", :placeholder => "Name", :type => "text"}
              %input.col-md-6{:name => "email", :placeholder => "E-mail", :type => "text"}
                %textarea.col-md-12{:name => "comment", :placeholder => "Nachricht", :rows => "7"}
                %input#submit.btn.btn-primary{:type => "submit", :value => "Absenden"}
      .col-md-5
        .titleborder.left
          %div
            %h4.padbot10 So sind wir erreichbar
        %i.fa.fa-map-marker
        %i Adresse
        \: 12345 Kattendorf, Buschweg 3
        %br
        %br
        %i.fa.fa-clock-o
        %i Erreichbarkeit
        \: Montag - Freitag, 9 - 21 Uhr
        %br
        %br
        %i.fa.fa-mobile-phone
        %i Telefon
        \: 0170 1234567
        %br
        %br
        %i.fa.fa-envelope
        %i E-mail
        %a{:href => "mailto:info@meinstarkesfahrrad.de"} info@meinstarkesfahrrad.de
        

app/views/home/index.html.haml
.headerimage.homeimg.text-center{:style => "background-image: url('#{image_path 'home-bg.jpg'}');"}
  .headercontent.home
    .container
      .row
        .col-md-12
          %h1{"data-scrollreveal" => "enter top over 1.9s after 0.2s", "data-scrollreveal-initialized" => true}
            -#%span.mein Mein
            = image_tag 'mein.png', class: 'mein'
            starkes Fahrrad
          %p.lead{"data-scrollreveal" => "enter bottom over 1.9s after 0.4s", "data-scrollreveal-initialized" => "true"}
            Dein Fahrrad wird zum eBike
          %a.homeimgbtn{"data-scrollreveal" => "enter bottom over 1.0s after 1.6s", "data-scrollreveal-initialized" => "true", "data-scroll" => true, :href => "#start"}
            Einfach losfahren

#start
#homepagetemplate.container.padtop10.padbot40
        
  = render partial: 'products/products'
  
  .clear
  .divider1

  = render partial: 'products/features'
  
  .clear
  .divider1
  
  = render partial: 'products/ratings'
            

app/views/home/show.html.haml
.singledownloadphp
  .headerimage{:style => "background-image: url('http://www.themepush.com/demo-kailo/wp-content/uploads/sites/6/2015/03/header.jpg');"}
    .headercontent
      .container
        .row
          .col-md-12
            .fleft
              %h1 eBike Einbauset

  .container.padtop50.padbot50
    .row
      .col-md-9
        #primary.content-area
          %main#main.site-main{:role => "main"}
            %article.contentdownloadphp
              .row
                .col-md-3
                  %span.entryitemname
                    %b Item:
                    eBike Einbauset
                    %br/
                  %span.entryprice
                    %b Preis
                    € 699
                    %br/
                  %span.entrysku
                    %b SKU:
                    set1
                    %br
                    %br
                  %span.entrybasicaddto
                    %a.edd-add-to-cart.button.edd-submit{:href => "#"}
                      %span.edd-add-to-cart-label.white In den Warenkorb
                .col-md-9
                  %img.attachment-post-thumbnail.wp-post-image{:alt => "5_1", :height => "370", :src => "/images/ebikekit.jpg", :width => "555"}
                    %p
                      This is your item description. Add as many info for your buyers about this product.
                    %p
                      Proin imperdiet cursus lacus, eu rutrum eros volutpat eget. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam a purus sed sapien congue pharetra. Proin tellus ligula, tincidunt at ante in, suscipit pretium nulla. Fusce nec scelerisque turpis. Proin id efficitur tortor.
                    %p
                      Nullam nec augue nulla. Nunc quis diam ante. Nam sed feugiat nisl. Nunc eget lacus tincidunt, feugiat enim non, volutpat tellus. Vivamus at cursus mi. Vivamus eu placerat odio. Curabitur malesuada consectetur dui, quis mollis velit vulputate in. Ut molestie a libero eget aliquet. Pellentesque at turpis placerat, porta dolor eu, scelerisque nisl.
                    %form.edd_download_purchase_form{:method => "post"}
                      .edd_purchase_submit_wrapper
                        %a.edd-add-to-cart.button.edd-submit{:href => "#"}
                          %span.edd-add-to-cart-label.white In den Warenkorb

              .row
                .col-md-12.padtop10
                  %h5.section-title.related-entries-title YOU MAY ALSO LIKE
                  %ul.related-entries
                    %li
                      .relatedinner
                        %a.related-entry-thumb{:href => "#", :rel => "bookmark", :title => "Bananas"}
                          %img.attachment-digitalstore_thumb_155x156.wp-post-image{:alt => "168_1", :height => "370", :src => "http://www.themepush.com/demo-kailo/wp-content/uploads/sites/6/edd/2015/03/168_1.jpg", :title => "Bananas", :width => "555"}
                            .edd-the-price
                              $6.50
                        %a.related-entry-title{:href => "#", :rel => "bookmark", :title => "Bananas"} Bananas
                    %li
                      .relatedinner
                        %a.related-entry-thumb{:href => "#", :rel => "bookmark", :title => "Old Game"}
                          %img.attachment-digitalstore_thumb_155x156.wp-post-image{:alt => "181_1", :height => "370", :src => "http://www.themepush.com/demo-kailo/wp-content/uploads/sites/6/edd/2015/03/181_1.jpg", :title => "Old Game", :width => "555"}
                            .edd-the-price
                              $33.00
                        %a.related-entry-title{:href => "#", :rel => "bookmark", :title => "Old Game"} Old Game
                    %li
                      .relatedinner
                        %a.related-entry-thumb{:href => "#", :rel => "bookmark", :title => "Eyes Wide Shut"}
                          %img.attachment-digitalstore_thumb_155x156.wp-post-image{:alt => "172_1", :height => "370", :src => "http://www.themepush.com/demo-kailo/wp-content/uploads/sites/6/edd/2015/03/172_1.jpg", :title => "Eyes Wide Shut", :width => "555"}
                            .edd-the-price
                              $17.00
                        %a.related-entry-title{:href => "#", :rel => "bookmark", :title => "Eyes Wide Shut"} Eyes Wide Shut
                  .clearfix

      .col-md-3
        #secondary.widget-area{:role => "complementary"}
          %aside.widget.widget_edd_cart_widget
            %h1.widget-title.section-title
              %span Mein Warenkorb
            %p.edd-cart-number-of-items
              Number of items in cart:
              %span.edd-cart-quantity 2
            %ul.edd-cart
              %li.edd-cart-item
                %span.edd-cart-item-title eBike Set
                %span.edd-cart-item-separator -
                %span.edd-cart-item-price &nbsp;€699,00&nbsp;
                %span.edd-cart-item-separator -
                %a.edd-remove-from-cart{:role => "#"} remove
              %li.edd-cart-item
                %span.edd-cart-item-title eBike Set mit Einbau
                %span.edd-cart-item-separator -
                %span.edd-cart-item-price &nbsp;€999,00&nbsp;
                %span.edd-cart-item-separator -
                %a.edd-remove-from-cart{:href => "#"} remove
              %li.cart_item.edd_subtotal
                Subtotal:
                %span.subtotal €0.000,00
              %li.cart_item.edd_checkout
                %a{:href => "#"} Jetzt Bestellen

app/views/layouts/application.html.haml
!!!
%html{lang: "de-DE"}
  %head
    %meta{charset: "UTF-8"}
    %meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0", name: "viewport"}
    %link{href: image_path('favicon.ico'), rel: "shortcut icon"}
    %title Mein starkes Fahrrad
    %link{:href => "http://fonts.googleapis.com/css?family=Raleway:400,300,500,600,700,800,900", :rel => "stylesheet", :type => "text/css"}
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
    
  %body
    .boxedlayout
      
      = render 'shared/header'
      
      = yield
      
      = render 'shared/footer'

:javascript
  document.write=function() {};
  document.writeln=function() {};
= javascript_include_tag 'application'

app/views/products/_features.html.haml
.row.text-center.seactionitemfeatures
  .narrowheader
    %h2.maintitle PRODUCT FEATURES
    56.000 customers cant be wrong. We offer free lifetime support and updates for all our items! SOME VERY NICE MOTTO TO EXIT. MAKE YOUR VISITORS LOVE THE PRODUCTS!
.col-md-4
  .featurebox
    %h2
      %i.fa.fa-gift
      Support
    Duis suscipit dapibus massa, in placerat metus iaculis ut. Praesent semper risus elit. Nam rutrum ipsum id sagittis egestas ulla eget nunc.
.col-md-4
  .featurebox
    %h2
      %i.fa.fa-trophy
      Security
    Duis suscipit dapibus massa, in placerat metus iaculis ut. Praesent semper risus elit. Nam rutrum ipsum id sagittis egestas ulla eget nunc.
.col-md-4
  .featurebox
    %h2
      %i.fa.fa-bullhorn
      Easy Install
    Duis suscipit dapibus massa, in placerat metus iaculis ut. Praesent semper risus elit. Nam rutrum ipsum id sagittis egestas ulla eget nunc.
.col-md-4
  .featurebox
    %h2
      %i.fa.fa-cogs
      Options
    Duis suscipit dapibus massa, in placerat metus iaculis ut. Praesent semper risus elit. Nam rutrum ipsum id sagittis egestas ulla eget nunc.
.col-md-4
  .featurebox
    %h2
      %i.fa.fa-anchor
      More
    Duis suscipit dapibus massa, in placerat metus iaculis ut. Praesent semper risus elit. Nam rutrum ipsum id sagittis egestas ulla eget nunc.
.col-md-4
  .featurebox
    %h2
      %i.fa.fa-cloud-download
      Built for you
    Duis suscipit dapibus massa, in placerat metus iaculis ut. Praesent semper risus elit. Nam rutrum ipsum id sagittis egestas ulla eget nunc.

app/views/products/_product.html.haml
.wowitembox
  .wowitemboxinner
    .imagearea
      %img.attachment-post-thumbnail.wp-post-image{:alt => "163_1", :height => "370", :src => "/images/set.jpeg", :width => "555"}
        .caption
          .blur
          .caption-text
            .captionbuttons
              = link_to url_for(action: 'show'), class: 'captiondetails' do
                %i.fa.fa-link
                Details
    .notesarea
      = link_to url_for(action: 'show') do
        %h2 Einbau-Set
      .description
        %p
          Sed ac scelerisque ligula, ac aliquam ligula. Vivamus ut pellentesque nisi, vel com.
      .notesbottom
        .price.fleft
          ab €699.00
        .cart.fright
          = link_to url_for(action: 'show'), class: 'edd-add-to-cart' do
            %span.edd-add-to-cart-label Jetzt bestellen
        .clearfix

app/views/products/_product2.html.haml
.wowitembox
  .wowitemboxinner
    .imagearea
      %img.attachment-post-thumbnail.wp-post-image{:alt => "163_1", :height => "370", :src => "/images/month.png", :width => "555"}
        .caption
          .blur
          .caption-text
            .captionbuttons
              = link_to url_for(action: 'show'), class: 'captiondetails' do
                %i.fa.fa-link
                Details
    .notesarea
      = link_to url_for(action: 'show') do
        %h2 Einen Monat eBike fahren
      .description
        %p
          Fahre einen Monat mit Deinem eigenen Fahrrad eBike. Die günstige Variante, um z. B. auf einer ausgedehnten Tour zu erleben, wie stark Dein Fahrrad sein kann.
      .notesbottom
        .price.fleft
          ab €99.00
        .cart.fright
          = link_to url_for(action: 'show'), class: 'edd-add-to-cart' do
            %span.edd-add-to-cart-label Jetzt bestellen
        .clearfix

app/views/products/_products.html.haml
.row
  .col-md-12
    .clear.text-center.sectionlatestitems
      %h2.maintitle Unsere Angebote
      .separatr
        %span
          %a.view-all{:href => "shop.html"}
            %i.fa.fa-reorder

    .wowitemboxlist.sectionlatestitems.clear{:style => "position: relative; height: 2156px;"}

      = render partial: 'products/product2'

      = render partial: 'products/product'
      
      = render partial: 'products/product'
      
      = render partial: 'products/product'

app/views/products/_ratings.html.haml
.row
  .col-md-12
    .clear.text-center.sectionlatestitems
      %h2.maintitle Bewertungen
      .separatr
        %span
          %a.view-all
            %i.fa.fa-user
    .well
      "Ich war erstaunt wie einfach der Einbau des Sets ging. So viel Spaß beim Fahrradfahren. Endlich fährt mein Mann nicht immer 50m vor mir her. Vielen Dank für dieses tolle Produkt!"
      %br
      %i.pull-right 
        %i.fa.fa-star
        %i.fa.fa-star
        %i.fa.fa-star
        %i.fa.fa-star        
        \-- Hannelore Meisner, Kiel

    .well
      "Vor nicht einmal einem Jahr habe ich mir ein neues Fahrrad gekauft. Es wäre schade gewesen, dieses gegen ein eBike auszutauschen. Dank Ihres Umbausets habe ich jetzt genau das Fahrrad, das ich mir immer gewünscht habe - stark!"
      %br
      %i.pull-right 
        %i.fa.fa-star
        %i.fa.fa-star
        %i.fa.fa-star
        %i.fa.fa-star
        \-- Manuel Senftenberg, Starnberg

app/views/shared/_footer.html.haml
%footer.themefooter.section.medium-padding.bg-graphite
  .container
    .section-inner.row
      .column.column-1.col-md-4.rightbd
        .widgets
          .widget.widget_text
            .widget-content
              %h3.widget-title Über &nbsp; “Mein starkes Fahrrad”
              .textwidget
                Duis suscipit dapibus massa, in placerat metus iaculis ut. Praesent semper risus elit. Nam rutrum ipsum id sagittis egestas ulla eget nunc.
            .clear
      / /footer-a
      .column.column-1.col-md-4.rightbd
        .widgets
          .widget.widget_wysija
            .widget-content
              %h3.widget-title Subscribe to our Newsletter
              .widget_wysija_cont
                %form.widget_wysija
                  Subscribe to our newsletter and join our 1234 subscribers.
                  %p.wysija-paragraph
                    %label
                      Email
                      %span.wysija-required *
                    %input.wysija-input{:class => "validate[required,custom[email]]", :name => "", :title => "Email", :type => "text", :value => ""}
                  %input.wysija-submit.wysija-submit-field{:type => "submit", :value => "Subscribe!"}
            .clear
      / /footer-b
      .column.column-1.col-md-4
        .widgets
          .widget.widget_edd_categories_tags_widget
            .widget-content
              %h3.widget-title Categories
              %ul.edd-taxonomy-widget
                %li
                  %a{:href => "index.html#"} Sets
                %li
                  %a{:href => "index.html#"} Services
                %li
                  %a{:href => "index.html#"} Subscription
            .clear
      / /footer-c
      .clear
    / /footer-inner
  / /grid
  .sectioncredits
    .container
      .row
        .col-md-12
          %span.credits-left.fleft
            2015 © All Rights Reserved, Mein starkes Fahrrad UG (haftungsbeschränkt)
          %ul.footermenu.fright
            %li
              %a{:href => "index.html"} Home
            %li
              %a{:href => "shop.html"} Shop
            %li
              %a{:href => "blog.html"} Blog
            %li
              %a{:href => "myaccount.html"} My Account
        .clear
    / /grid
  / /sectioncredits
/ /footer

app/views/shared/_header.html.haml
%nav#wow-menu.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        = image_tag 'logo.png'

    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul#menu-top.nav.navbar-nav.navbar-right
        %li{class: controller_name == 'home' && 'active'}
          = link_to "Home", root_path
        %li{class: controller_name == 'blogs' && 'active'}
          = link_to "Blog", blogs_path
        %li{class: controller_name == 'contact' && 'active'}
          = link_to "Kontakt", url_for( controller: 'contact')
        %li{class: (controller_name == 'checkout') && 'active'}
          = link_to url_for( controller: 'checkout') do
            %i.fa.fa-shopping-cart
            Warenkorb (2)